<a href="https://colab.research.google.com/github/minjun771/linear/blob/main/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%981%EC%8B%A4%EC%8A%B56.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.set_printoptions(suppress=True, precision=2)

A = np.array([
    [1, 2, 3],
    [2, 5, 3],
    [1, 0, 8]
], dtype=float)

I = np.eye(3)

AI = np.hstack((A, I))

def show_matrix(operation):
    print(f"\n{operation}")
    print(AI)

print("초기 첨가행렬 [A | I]")
print(AI)

AI[1] = (-2) * AI[0] + AI[1]
show_matrix("R2 ← (-2)R1 + R2")

AI[2] = (-1) * AI[0] + AI[2]
show_matrix("R3 ← (-1)R1 + R3")

AI[2] = 2 * AI[1] + AI[2]
show_matrix("R3 ← 2R2 + R3")

AI[2] = (-1) * AI[2]
show_matrix("R3 ← (-1)R3")

AI[1] = AI[1] + 3 * AI[2]
show_matrix("R2 ← R2 + 3R3")

AI[0] = AI[0] - 3 * AI[2]
show_matrix("R1 ← R1 - 3R3")

AI[0] = AI[0] - 2 * AI[1]
show_matrix("R1 ← R1 - 2R2")

A_inverse = AI[:, 3:]

print("\n최종 첨가행렬 [I | A^(-1)]")
print(AI)

print("\nA의 역행렬")
print(A_inverse)

print("\n검산: A × A^(-1)")
print(A @ A_inverse)

초기 첨가행렬 [A | I]
[[1. 2. 3. 1. 0. 0.]
 [2. 5. 3. 0. 1. 0.]
 [1. 0. 8. 0. 0. 1.]]

R2 ← (-2)R1 + R2
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1. -3. -2.  1.  0.]
 [ 1.  0.  8.  0.  0.  1.]]

R3 ← (-1)R1 + R3
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1. -3. -2.  1.  0.]
 [ 0. -2.  5. -1.  0.  1.]]

R3 ← 2R2 + R3
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1. -3. -2.  1.  0.]
 [ 0.  0. -1. -5.  2.  1.]]

R3 ← (-1)R3
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1. -3. -2.  1.  0.]
 [-0. -0.  1.  5. -2. -1.]]

R2 ← R2 + 3R3
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  0. 13. -5. -3.]
 [-0. -0.  1.  5. -2. -1.]]

R1 ← R1 - 3R3
[[  1.   2.   0. -14.   6.   3.]
 [  0.   1.   0.  13.  -5.  -3.]
 [ -0.  -0.   1.   5.  -2.  -1.]]

R1 ← R1 - 2R2
[[  1.   0.   0. -40.  16.   9.]
 [  0.   1.   0.  13.  -5.  -3.]
 [ -0.  -0.   1.   5.  -2.  -1.]]

최종 첨가행렬 [I | A^(-1)]
[[  1.   0.   0. -40.  16.   9.]
 [  0.   1.   0.  13.  -5.  -3.]
 [ -0.  -0.   1.   5.  -2.  -1.]]

A의 역행렬
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]

검산: A × A^(-1)


In [3]:
import numpy as np

np.set_printoptions(suppress=True, precision=2)

A = np.array([
    [1, -3, 4],
    [2, -5, 7],
    [0, -1, 1]
], dtype=float)

I = np.eye(3)

AI = np.hstack((A, I))

def show_matrix(title):
    print(f"\n{title}")

    for row in AI:
        left = " ".join(f"{value:6.1f}" for value in row[:3])
        right = " ".join(f"{value:6.1f}" for value in row[3:])
        print(f"[{left} | {right}]")

show_matrix("초기 첨가행렬 [A | I]")

AI[1] = (-2) * AI[0] + AI[1]
show_matrix("1단계: R2 ← (-2)R1 + R2")

AI[2] = AI[1] + AI[2]
show_matrix("2단계: R3 ← R2 + R3")

AI[0] = 3 * AI[1] + AI[0]
show_matrix("3단계: R1 ← 3R2 + R1")

left_matrix = AI[:, :3]
right_matrix = AI[:, 3:]

print("\n행 연산 후 왼쪽 행렬")
print(left_matrix)
print("\n행 연산 후 오른쪽 행렬")
print(right_matrix)

if np.linalg.matrix_rank(A) < A.shape[0]:
    print("\n판정 결과")
    print("A의 행들이 선형종속입니다.")
    print("왼쪽 행렬에 모든 원소가 0인 행이 발생했습니다.")
    print("따라서 A를 단위행렬로 만들 수 없습니다.")
    print("행렬 A의 역행렬은 존재하지 않습니다.")
else:
    A_inverse = right_matrix
    print("\nA의 역행렬")
    print(A_inverse)

det_A = np.linalg.det(A)
print("det(A) =", round(det_A))


초기 첨가행렬 [A | I]
[   1.0   -3.0    4.0 |    1.0    0.0    0.0]
[   2.0   -5.0    7.0 |    0.0    1.0    0.0]
[   0.0   -1.0    1.0 |    0.0    0.0    1.0]

1단계: R2 ← (-2)R1 + R2
[   1.0   -3.0    4.0 |    1.0    0.0    0.0]
[   0.0    1.0   -1.0 |   -2.0    1.0    0.0]
[   0.0   -1.0    1.0 |    0.0    0.0    1.0]

2단계: R3 ← R2 + R3
[   1.0   -3.0    4.0 |    1.0    0.0    0.0]
[   0.0    1.0   -1.0 |   -2.0    1.0    0.0]
[   0.0    0.0    0.0 |   -2.0    1.0    1.0]

3단계: R1 ← 3R2 + R1
[   1.0    0.0    1.0 |   -5.0    3.0    0.0]
[   0.0    1.0   -1.0 |   -2.0    1.0    0.0]
[   0.0    0.0    0.0 |   -2.0    1.0    1.0]

행 연산 후 왼쪽 행렬
[[ 1.  0.  1.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]

행 연산 후 오른쪽 행렬
[[-5.  3.  0.]
 [-2.  1.  0.]
 [-2.  1.  1.]]

판정 결과
A의 행들이 선형종속입니다.
왼쪽 행렬에 모든 원소가 0인 행이 발생했습니다.
따라서 A를 단위행렬로 만들 수 없습니다.
행렬 A의 역행렬은 존재하지 않습니다.
det(A) = 0


In [6]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 5, 3],
    [1, 0, 8]
], dtype=float)

def get_minor(matrix, row, col):
  return np.delete(
      np.delete(matrix, row, axis=0),
      col,
      axis=1
  )
def cofactor_matrix(matrix):
  n = matrix.shape[0]
  C = np.zeros((n,n))
  for i in range(n):
    for j in range(n):
      minor = get_minor(matrix, i, j)
      C[i,j] = ((-1) ** (i+j)) * np.linalg.det(minor)
  return C

det_A = round(np.linalg.det(A))

if det_A == 0:
  print("행렬식이 0이므로 역행렬이 존재하지 않습니다.")

else:
  C = cofactor_matrix(A)

  adj_A = C.T

  inverse_A = (1/ det_A ) * adj_A

  C= np.round(C, 10)
  adj_A = np.round(adj_A, 10)
  inverse_A = np.round(inverse_A, 10)

  print("행렬 A")
  print(A)
  print("\n행렬식 det(A)")
  print(det_A)
  print("\n여인수행렬 C")
  print(C)
  print("\n수반행렬 adj(A)")
  print(adj_A)
  print("\n역행렬 A^(-1)")
  print(inverse_A)
  print('\n검산 A x A^(-1)')
  print(np.round(A @ inverse_A , 10))

행렬 A
[[1. 2. 3.]
 [2. 5. 3.]
 [1. 0. 8.]]

행렬식 det(A)
-1

여인수행렬 C
[[ 40. -13.  -5.]
 [-16.   5.   2.]
 [ -9.   3.   1.]]

수반행렬 adj(A)
[[ 40. -16.  -9.]
 [-13.   5.   3.]
 [ -5.   2.   1.]]

역행렬 A^(-1)
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]

검산 A x A^(-1)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import numpy as np

np.set_printoptions(suppress=True, precision=2)

A = np.array([
    [1, 2, 3],
    [1, 3, 6],
    [2, 6, 13]
], dtype=float)

b = np.array([
    [1],
    [3],
    [5]
], dtype=float)

print("계수행렬 A")
print(A)
print("\n상수벡터 b")
print(b)

det_A = np.linalg.det(A)
print("\n행렬식 det(A)")
print(round(det_A, 10))

if np.isclose(det_A, 0):
    print("\ndet(A) = 0이므로 역행렬이 존재하지 않습니다.")
else:
    A_inverse = np.linalg.inv(A)
    print("\nA의 역행렬")
    print(A_inverse)

    X = A_inverse @ b
    print("\n선형시스템의 해")
    print(X)

    x, y, z = X.flatten()
    print(f"\nx = {x:.0f}")
    print(f"y = {y:.0f}")
    print(f"z = {z:.0f}")

print("\n검산 결과 A @ X")
print(A @ X)

계수행렬 A
[[ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 2.  6. 13.]]

상수벡터 b
[[1.]
 [3.]
 [5.]]

행렬식 det(A)
1.0

A의 역행렬
[[ 3. -8.  3.]
 [-1.  7. -3.]
 [-0. -2.  1.]]

선형시스템의 해
[[-6.]
 [ 5.]
 [-1.]]

x = -6
y = 5
z = -1

검산 결과 A @ X
[[1.]
 [3.]
 [5.]]


In [8]:
def determinant_2x2(matrix):
    return (
        matrix[0][0] * matrix[1][1]
        - matrix[0][1] * matrix[1][0]
    )

A = [
    [3, -2],
    [-5, 4]
]

b = [6, 8]

A1 = [
    [b[0], A[0][1]],
    [b[1], A[1][1]]
]

A2 = [
    [A[0][0], b[0]],
    [A[1][0], b[1]]
]

D = determinant_2x2(A)
D1 = determinant_2x2(A1)
D2 = determinant_2x2(A2)

print("계수행렬 A =", A)
print("A1 =", A1)
print("A2 =", A2)
print("det(A) =", D)
print("det(A1) =", D1)
print("det(A2) =", D2)

if D == 0:
    print("det(A)가 0이므로 크래머의 규칙을 적용할 수 없습니다.")
else:
    x1 = D1 / D
    x2 = D2 / D
    print("크래머의 규칙 계산")
    print(f"x1 = det(A1) / det(A) = {D1} / {D} = {x1}")
    print(f"x2 = det(A2) / det(A) = {D2} / {D} = {x2}")
    print("선형시스템의 해")
    print(f"x1 = {x1}")
    print(f"x2 = {x2}")

    result1 = 3 * x1 - 2 * x2
    result2 = -5 * x1 + 4 * x2
    print("검산")
    print(f"3x1 - 2x2 = {result1}")
    print(f"-5x1 + 4x2 = {result2}")

계수행렬 A = [[3, -2], [-5, 4]]
A1 = [[6, -2], [8, 4]]
A2 = [[3, 6], [-5, 8]]
det(A) = 2
det(A1) = 40
det(A2) = 54
크래머의 규칙 계산
x1 = det(A1) / det(A) = 40 / 2 = 20.0
x2 = det(A2) / det(A) = 54 / 2 = 27.0
선형시스템의 해
x1 = 20.0
x2 = 27.0
검산
3x1 - 2x2 = 6.0
-5x1 + 4x2 = 8.0


In [10]:
import numpy as np

np.set_printoptions(suppress=True, precision=2)

A = np.array([
    [1, -1, 1],
    [1, 1, -2],
    [1, 2, 1]
], dtype=float)

b = np.array([0, 1, 6], dtype=float)

D = round(np.linalg.det(A))

print("계수행렬 A")
print(A)
print("\n상수벡터 b")
print(b)
print(f"\nD = det(A) = {D}")

if D == 0:
    print("det(A)가 0이므로 크래머의 규칙을 적용할 수 없습니다.")
else:
    determinants = []
    solution = []

    for i in range(A.shape[1]):
        Ai = A.copy()
        Ai[:, i] = b

        Di = round(np.linalg.det(Ai))
        xi = Di / D
        determinants.append(Di)
        solution.append(xi)

        print(f"\nA{i + 1}: {i + 1}번째 열을 b로 교체")
        print(Ai)
        print(f"D{i + 1} = det(A{i + 1}) = {Di}")
        print(
            f"x{i + 1} = D{i + 1}/D "
            f"= {Di}/{D} = {xi}"
        )

    solution = np.array(solution)

    print("\n최종 해")
    for i, value in enumerate(solution, start=1):
        print(f"x{i} = {value}")

    print("\n검산 결과 A @ x")
    print(A @ solution)
    print("\n원래 상수벡터 b")
    print(b)

계수행렬 A
[[ 1. -1.  1.]
 [ 1.  1. -2.]
 [ 1.  2.  1.]]

상수벡터 b
[0. 1. 6.]

D = det(A) = 9

A1: 1번째 열을 b로 교체
[[ 0. -1.  1.]
 [ 1.  1. -2.]
 [ 6.  2.  1.]]
D1 = det(A1) = 9
x1 = D1/D = 9/9 = 1.0

A2: 2번째 열을 b로 교체
[[ 1.  0.  1.]
 [ 1.  1. -2.]
 [ 1.  6.  1.]]
D2 = det(A2) = 18
x2 = D2/D = 18/9 = 2.0

A3: 3번째 열을 b로 교체
[[ 1. -1.  0.]
 [ 1.  1.  1.]
 [ 1.  2.  6.]]
D3 = det(A3) = 9
x3 = D3/D = 9/9 = 1.0

최종 해
x1 = 1.0
x2 = 2.0
x3 = 1.0

검산 결과 A @ x
[0. 1. 6.]

원래 상수벡터 b
[0. 1. 6.]


In [11]:
import math

def determinant_2x2(matrix):
    return (
        matrix[0][0] * matrix[1][1]
        - matrix[0][1] * matrix[1][0]
    )

angle_25 = math.radians(25)
angle_15 = math.radians(15)

A = [
    [math.cos(angle_25), -math.cos(angle_15)],
    [math.sin(angle_25), math.sin(angle_15)]
]

b = [0, 30]

A1 = [
    [b[0], A[0][1]],
    [b[1], A[1][1]]
]

A2 = [
    [A[0][0], b[0]],
    [A[1][0], b[1]]
]

D = determinant_2x2(A)
D1 = determinant_2x2(A1)
D2 = determinant_2x2(A2)

print("계수행렬 A")
for row in A:
    print(row)
print("\nA1: 첫 번째 열을 b로 교체")
for row in A1:
    print(row)
print("\nA2: 두 번째 열을 b로 교체")
for row in A2:
    print(row)
print(f"\nD = det(A) = {D:.6f}")
print(f"D1 = det(A1) = {D1:.6f}")
print(f"D2 = det(A2) = {D2:.6f}")

if math.isclose(D, 0.0, abs_tol=1e-12):
    print("\ndet(A)가 0이므로 유일한 해가 없습니다.")
else:
    T1 = D1 / D
    T2 = D2 / D
    print("\n크래머의 규칙 계산")
    print(f"T1 = D1 / D = {D1:.6f} / {D:.6f}")
    print(f"T1 = {T1:.4f}")
    print(f"\nT2 = D2 / D = {D2:.6f} / {D:.6f}")
    print(f"T2 = {T2:.4f}")

    equation1 = (
        math.cos(angle_25) * T1
        - math.cos(angle_15) * T2
    )
    equation2 = (
        math.sin(angle_25) * T1
        + math.sin(angle_15) * T2
    )
    print("\n검산")
    print(f"수평 방향 합 = {equation1:.6f}")
    print(f"수직 방향 합 = {equation2:.6f}")

계수행렬 A
[0.9063077870366499, -0.9659258262890683]
[0.42261826174069944, 0.25881904510252074]

A1: 첫 번째 열을 b로 교체
[0, -0.9659258262890683]
[30, 0.25881904510252074]

A2: 두 번째 열을 b로 교체
[0.9063077870366499, 0]
[0.42261826174069944, 30]

D = det(A) = 0.642788
D1 = det(A1) = 28.977775
D2 = det(A2) = 27.189234

크래머의 규칙 계산
T1 = D1 / D = 28.977775 / 0.642788
T1 = 45.0814

T2 = D2 / D = 27.189234 / 0.642788
T2 = 42.2989

검산
수평 방향 합 = 0.000000
수직 방향 합 = 30.000000


In [13]:
import numpy as np

u1 = np.array([1, 1, 0], dtype=float)
u2 = np.array([1, 1, 1], dtype=float)
u3 = np.array([0, 2, 3], dtype=float)

A = np.array([
    u1,
    u2,
    u3
])

print("벡터 행렬 A")
print(A)

det_A = np.linalg.det(A)
det_A = round(det_A, 10)
volume = abs(det_A)

print("\n행렬식 det (A)")
print(det_A)
print("\n평행육면체 S의 체적 ")
print(volume)

벡터 행렬 A
[[1. 1. 0.]
 [1. 1. 1.]
 [0. 2. 3.]]

행렬식 det (A)
-2.0

평행육면체 S의 체적 
2.0
